version: "3.7"

services:
  recruitment-mysql-db:
    image: mysql:latest
    container_name: recruitment-mysql-db
    ports:
      - "3307:3306"
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command:
      - --character-set-server=utf8mb4
    volumes:
      - mysql-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-volume:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    build:
      context: ./server
      target: development
    container_name: server
    ports:
      - "4003:4003"
    restart: always
    depends_on:
      recruitment-mysql-db:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    volumes:
      - ./server/src:/app/src
    env_file:
      - .env
    environment:
      - SYNC_DATA

volumes:
  mysql-volume:
  mongo-volume: